Repository imran1289-ah/team_Taiga-soen341project2022, pull requests merged in 2022-02, with the labels that each got.

#21 Add database and API design document from Feb 1 meeting
  Sprint 2/Database + API Design.txt
Labels: documentation

#26 Connection between server/client and header navbar
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.js
  src/client/src/Header.css
  src/client/src/Header.js
  src/client/src/index.js
  src/server/index.js
  src/server/package-lock.json
  src/server/package.json
Labels: task:backend, task:frontend

#38 Added the home page
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.css
  src/client/src/App.js
  src/client/src/Footer.css
  src/client/src/Footer.js
  src/client/src/Header.css
  src/client/src/Header.js
  src/client/src/Login.css
  src/client/src/Login.js
  src/client/src/SlideShow.css
  src/client/src/SlideShow.js
  src/client/src/Taiga_Logo.png
  src/client/src/Types.css
  src/client/src/Types.js
Labels: task:frontend, userstory#1

#39 Add passport-local authentication and session management to server
  src/server/index.js
  src/server/package-lock.json
  src/server/package.json
Labels: task:backend, userstory#1

#41 Connect Login and register to server
  src/client/package-lock.json
  src/client/package.json
  src/client/src/App.css
  src/client/src/App.js
  src/client/src/Login.css
  src/client/src/Login.js
  src/server/index.js
Labels: task:frontend, userstory#1, userstory#2

#47 Add and style login and register messages #10, #29
  src/client/src/Login.css
  src/client/src/Login.js
Labels: task:frontend, userstory#1, userstory#2

#46 Implement user login, registration, logout
  src/server/auth.js
  src/server/controllers/userController.js
  src/server/index.js
  src/server/models/user.js
  src/server/package-lock.json
  src/server/package.json
  src/server/routes/userRoutes.js
Labels: task:backend, userstory#1, userstory#2

#65 Adding the Summary for sprint3
  Sprint 2/Plan_For_Sprint3.md
Labels: documentation
