Repository imran1289-ah/team_Taiga-soen341project2022, pull requests merged in 2022-03, with the labels that each got.

#68 Adding User Story 2 #43
  src/client/src/AddProduct.js
  src/client/src/App.js
  src/client/src/Bookslist.js
  src/client/src/Clotheslist.js
  src/client/src/EditProduct.js
  src/client/src/Electronicslist.js
  src/client/src/Furniturelist.js
  src/client/src/Grocerylist.js
  src/client/src/Header.js
  src/client/src/SellerMenu.css
  src/client/src/SellerMenu.js
  src/client/src/Toyslist.js
  src/server/index.js
  src/server/models/products.js
  src/server/products.json
  src/server/routes/productsRoutes.js
Labels: task:backend, task:frontend, userstory#2

#76 Acceptance Tests for all user stories #69
  Sprint 3/AcceptanceTests_AllUserStories.pdf
Labels: documentation

#95 Add automated testing for user stories 1 and 2
  src/server/index.js
  src/server/routes/productsRoutes.js
  test/README.md
  test/login.test.js
  test/package-lock.json
  test/package.json
  test/product.test.js
Labels: userstory#1, userstory#2, Sellers posting products
